const SCAN_DATA = [
    // 1. MARKETING EFFICIENCY (Weekly)
    {
        id: "mkt_01",
        section: "Marketing Efficiency",
        kpi_name: "Enquiries",
        current_value: "142",
        trend: "up",
        trend_text: "+8 vs last week",
        status: "green",
        frequency: "W",
        explanation: "Inbound interest stayed strong after the campus open day; website leads were the main driver and referral enquiries improved for a second week.",
        action_text: "Hold the same follow-up cadence and add a second call window for web leads within 24 hours.",
        detail_link: "drilldown-kpi.html?kpi=mkt_01"
    },
    {
        id: "mkt_02",
        section: "Marketing Efficiency",
        kpi_name: "Conversions (E-E)",
        current_value: "18.4%",
        trend: "down",
        trend_text: "-2.1 pts vs last week",
        status: "amber",
        frequency: "W",
        explanation: "Follow-up speed slipped in week 9, slowing conversions; response times after 4pm are the biggest contributor to the drop.",
        action_text: "Shift two counselors to late-afternoon coverage and automate 48-hour reminders.",
        detail_link: "drilldown-kpi.html?kpi=mkt_02"
    },
    {
        id: "mkt_03",
        section: "Marketing Efficiency",
        kpi_name: "Applications",
        current_value: "61",
        trend: "up",
        trend_text: "+5 vs last week",
        status: "green",
        frequency: "W",
        explanation: "Application starts recovered after targeted email nudges; the reminder cadence lifted conversions from open-day attendees.",
        action_text: "Keep the nudge cadence and add a short counselor call for undecided families.",
        detail_link: "drilldown-kpi.html?kpi=mkt_03"
    },
    {
        id: "mkt_04",
        section: "Marketing Efficiency",
        kpi_name: "FTEs (student count)",
        current_value: "1,148",
        trend: "flat",
        trend_text: "+2 vs last week",
        status: "green",
        frequency: "W",
        explanation: "Enrollment levels are holding steady ahead of mid-term; small net gains are coming from Primary transfers.",
        action_text: "Track transfer pipeline weekly and prioritize Grade 3-5 conversion calls.",
        detail_link: "drilldown-kpi.html?kpi=mkt_04"
    },

    // 2. SCHOOL PROPOSITION
    {
        id: "prop_01",
        section: "School Proposition",
        kpi_name: "Attendance %",
        current_value: "94.6%",
        trend: "down",
        trend_text: "-0.4 pts vs last week",
        status: "amber",
        frequency: "W",
        explanation: "Short-term absences rose during the mid-term break week; Year 10 attendance dipped the most after assessments.",
        action_text: "Run a targeted attendance push for Years 10-11 and re-engage chronic absences.",
        detail_link: "drilldown-kpi.html?kpi=prop_01"
    },
    {
        id: "prop_02",
        section: "School Proposition",
        kpi_name: "Student Incidents",
        current_value: "9",
        trend: "down",
        trend_text: "-3 vs last week",
        status: "green",
        frequency: "W",
        explanation: "Pastoral interventions reduced repeat incidents; corridor supervision and check-ins lowered repeat cases.",
        action_text: "Maintain corridor coverage and reinforce peer mediation sessions weekly.",
        detail_link: "drilldown-kpi.html?kpi=prop_02"
    },
    {
        id: "prop_03",
        section: "School Proposition",
        kpi_name: "Performance of Key Qualifications",
        current_value: "72% A*-B",
        trend: "down",
        trend_text: "-3 pts vs last year",
        status: "amber",
        frequency: "A",
        explanation: "Math and science scores need focused support this term; mock exam results show a 3-point gap vs target.",
        action_text: "Schedule booster sessions and align exam technique across departments.",
        detail_link: "drilldown-kpi.html?kpi=prop_03"
    },
    {
        id: "prop_04",
        section: "School Proposition",
        kpi_name: "University Destinations",
        current_value: "88% top-2 choice",
        trend: "up",
        trend_text: "+2 pts vs last year",
        status: "green",
        frequency: "A",
        explanation: "Early counseling boosted acceptance into first-choice offers; UK and US offers improved versus last year.",
        action_text: "Expand alumni mentoring and lock April university readiness workshops.",
        detail_link: "drilldown-kpi.html?kpi=prop_04"
    },

    // 3. SCHOOL PERFORMANCE (Financial / Operational)
    {
        id: "perf_01",
        section: "School Performance",
        kpi_name: "Capacity Creation",
        current_value: "94%",
        trend: "down",
        trend_text: "-1 pt vs last month",
        status: "amber",
        frequency: "M",
        explanation: "A few new sections are still awaiting final approvals; secondary expansion timelines slipped by two weeks.",
        action_text: "Accelerate approvals and finalize staffing for the new sections.",
        detail_link: "drilldown-kpi.html?kpi=perf_01"
    },
    {
        id: "perf_02",
        section: "School Performance",
        kpi_name: "Flowthrough %",
        current_value: "62%",
        trend: "up",
        trend_text: "+3 pts vs last month",
        status: "green",
        frequency: "M",
        explanation: "Operating costs held steady while fee income improved; tighter procurement drove a 1.5-point lift in margin.",
        action_text: "Sustain procurement controls and monitor utilities weekly.",
        detail_link: "drilldown-kpi.html?kpi=perf_02"
    },
    {
        id: "perf_03",
        section: "School Performance",
        kpi_name: "EBITDA",
        current_value: "GBP 1.2M",
        trend: "down",
        trend_text: "-GBP 0.15M vs budget",
        status: "red",
        frequency: "M",
        explanation: "Utility and staffing costs exceeded the monthly plan; overtime and utilities were both above forecast.",
        action_text: "Freeze discretionary overtime and renegotiate utility usage schedules.",
        detail_link: "drilldown-kpi.html?kpi=perf_03"
    },
    {
        id: "perf_04",
        section: "School Performance",
        kpi_name: "NPS",
        current_value: "29",
        trend: "down",
        trend_text: "-4 pts vs last year",
        status: "red",
        frequency: "A",
        explanation: "Communication and fee value perception softened; response time and fee transparency are the top detractor themes.",
        action_text: "Publish a monthly comms calendar and run a value-for-money forum.",
        detail_link: "drilldown-kpi.html?kpi=perf_04"
    },
    {
        id: "perf_05",
        section: "School Performance",
        kpi_name: "Fee Income Collection",
        current_value: "96.1%",
        trend: "down",
        trend_text: "-1.2 pts vs last month",
        status: "amber",
        frequency: "M",
        explanation: "Late payments increased in Grade 10 and Grade 11 cohorts; 12 families are now past due.",
        action_text: "Call top overdue accounts and refresh payment plans this week.",
        detail_link: "drilldown-kpi.html?kpi=perf_05"
    },
    {
        id: "perf_06",
        section: "School Performance",
        kpi_name: "Student Churn",
        current_value: "2.4%",
        trend: "down",
        trend_text: "-0.3 pts vs last month",
        status: "green",
        frequency: "M",
        explanation: "Exit interviews show improvements in pastoral support; relocation is still the top exit reason.",
        action_text: "Strengthen relocation support and track exit reasons monthly.",
        detail_link: "drilldown-kpi.html?kpi=perf_06"
    },

    // 4. TALENT / CAPABILITY
    {
        id: "tal_01",
        section: "Talent / Capability",
        kpi_name: "Employee Engagement",
        current_value: "71",
        trend: "down",
        trend_text: "-4 pts vs last survey",
        status: "amber",
        frequency: "A",
        explanation: "Support teams reported workload strain during exams; survey comments cite cover pressure and late meetings.",
        action_text: "Introduce workload check-ins and protect meeting-free windows.",
        detail_link: "drilldown-kpi.html?kpi=tal_01"
    },
    {
        id: "tal_02",
        section: "Talent / Capability",
        kpi_name: "Attrition %",
        current_value: "18%",
        trend: "up",
        trend_text: "+2.1 pts vs last month",
        status: "red",
        frequency: "M",
        explanation: "Mid-year departures rose in the primary division; three exits were linked to workload and commute.",
        action_text: "Launch stay interviews and adjust rota support for Primary teams.",
        detail_link: "drilldown-kpi.html?kpi=tal_02"
    },
    {
        id: "tal_03",
        section: "Talent / Capability",
        kpi_name: "Employee FTE",
        current_value: "176",
        trend: "up",
        trend_text: "+4 vs last month",
        status: "green",
        frequency: "M",
        explanation: "Recruitment closed key vacancies in learning support; vacancy rate dropped by three roles.",
        action_text: "Rebalance staffing across divisions and finalize cover schedule.",
        detail_link: "drilldown-kpi.html?kpi=tal_03"
    },
    {
        id: "tal_04",
        section: "Talent / Capability",
        kpi_name: "PTR (Pupil-Teacher Ratio)",
        current_value: "13.8:1",
        trend: "up",
        trend_text: "+0.6 vs last month",
        status: "amber",
        frequency: "M",
        explanation: "Secondary humanities classes are running slightly larger; timetable adjustments are still in progress.",
        action_text: "Revisit timetable allocations and reduce class sizes by one per section.",
        detail_link: "drilldown-kpi.html?kpi=tal_04"
    },
    {
        id: "tal_05",
        section: "Talent / Capability",
        kpi_name: "CBC Compliance",
        current_value: "92%",
        trend: "down",
        trend_text: "-1 pt vs last week",
        status: "green",
        frequency: "W",
        explanation: "Documentation is current for most teams, audit gaps closing; two CBC renewals are still outstanding.",
        action_text: "Close CBC renewals within 10 days and add a daily tracker.",
        detail_link: "drilldown-kpi.html?kpi=tal_05",
        is_compliance: true,
        compliance_status: "green"
    },
    {
        id: "tal_06",
        section: "Talent / Capability",
        kpi_name: "Safeguarding %",
        current_value: "76.2%",
        trend: "down",
        trend_text: "-4.8 pts vs last week",
        status: "red",
        frequency: "W",
        explanation: "Outstanding staff training renewals need urgent action; contractor onboarding is the main backlog.",
        action_text: "Mandate training completion by Friday and escalate contractor checks.",
        detail_link: "drilldown-kpi.html?kpi=tal_06",
        is_compliance: true,
        compliance_status: "red"
    }
];

const GLOBAL_CONFIG = {
    schoolName: "Lincoln Academy",
    region: "Florida Region",
    principalName: "Dr. Sarah Miller",
    warRoomThreshold: "red"
};
